from more_itertools import unzip
from functools import partial
from pathlib import Path
from snakemake.utils import min_version, validate
from scripts.python.common.config import (
    input_set,
    expand_rules,
    validate_inputs,
    validate_ebm_inputs,
    validate_ebm_features,
)

min_version("6.12")


configfile: "config/static.yml"


validate(config, "schemas/config-schema.yml")
validate_inputs(config)
validate_ebm_features(config)
validate_ebm_inputs(config)


################################################################################
# Paths

conf_paths = config["paths"]
resources_dir = Path(conf_paths["resources"])
results_dir = Path(conf_paths["results"])
scripts_root = Path("workflow/scripts")

# this is necessary as envs/scripts are apparently resolved locally in each rule
# file
def build_abs_path(relpath, basename):
    return str(relpath.resolve() / basename)


envs_path = partial(build_abs_path, Path("workflow/envs"))
python_path = partial(build_abs_path, scripts_root / "python")
sh_path = partial(build_abs_path, scripts_root / "shell")
rmd_path = partial(build_abs_path, scripts_root / "rmarkdown")


################################################################################
# Import Subworkflows


include: "rules/labels/parse_vcf.smk"
include: "rules/annotations/main.smk"
include: "rules/train_ebm.smk"


################################################################################
# Main Target


rule all:
    input:
        rules.all_summary.input,
        rules.all_ebm.input,


################################################################################
# Testing Targets


rule all_resources:
    input:
        expand(rules.download_query_vcf.output, input_key=[*config["inputs"]]),
        expand(rules.download_ref_sdf.output, ref_key=input_set(config, "ref")),
        expand(
            expand_rules(
                rules,
                ["download_bench_vcf", "download_bench_bed"],
                "output",
            ),
            bench_key=input_set(config, "benchmark"),
        ),
        # TODO all these implicitly depend on the reference
        rules.download_genome.output,
        rules.download_mappability_high.output,
        rules.download_mappability_low.output,
        rules.download_repeat_masker.output,
        rules.download_superdups.output,
        rules.download_tandem_repeats.output,
