################################################################################
# global pipeline config

variables:
  ENV_DIR: ./this-env
  TESTCONF: config/testing.yml
  # speed up cache compression
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

# only run this pipeline on master/default/feature branches
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^x_.*/
      when: never
    - when: always

image: condaforge/mambaforge:4.12.0-0

################################################################################
# reusable object to permit lazy coder syndrome

.smk_global_cache: &smk_global_cache
  paths:
    - this-env
  key:
    files:
      - env.yml

.smk_envs_cache: &smk_envs_cache
  paths:
    - .snakemake/conda
  key:
    files:
      - workflow/envs

.smk_resources_cache: &smk_resources_cache
  paths:
    - resources
  key:
    files:
      - config/testing.yml

.lint_cache: &lint_cache
  paths:
    - ./lint-*
  key:
    files:
      - workflow/scripts/python/*/env.yml
      - workflow/scripts/rmarkdown/*/env.yml

.activate_smk: &activate_smk
  before_script:
    - eval "$(${CONDA_DIR}/bin/conda shell.bash hook 2> /dev/null)"
    - conda activate $ENV_DIR

################################################################################
# set up global conda environment

# - ASSUME mamba is already installed on the system hosting the gitlab runner
# - ASSUME the cache will track any changes to env.yml and will force an update
#   if this changes
install_global_env:
  stage: test
  script:
    - >
      test -d $ENV_DIR
      && echo "Env already created"
      || mamba env create -f env.yml -p $ENV_DIR
  cache: 
    - <<: *smk_global_cache

################################################################################
# lint code

run_linters:
  stage: test
  script:
    - eval "$(${CONDA_DIR}/bin/conda shell.bash hook 2> /dev/null)"
    - ./setup_dev.sh ./lint
    - ./lint.sh ./lint
  cache:
    paths:
      - ./lint-*
    key:
      files:
        - workflow/scripts/python/*/env.yml
        - workflow/scripts/rmarkdown/*/env.yml

################################################################################
# test snakemake things

snakemake_dry:
  needs: [install_global_env]
  stage: test
  <<: *activate_smk
  script:
    - snakemake --use-conda -c 1 --configfile=$TESTCONF --dryrun
  cache:
    - <<: *smk_global_cache
      policy: pull
    - <<: *smk_envs_cache

snakemake_resources:
  needs: [snakemake_dry, install_global_env]
  stage: test
  <<: *activate_smk
  script:
    - snakemake -p --use-conda -c 8 --configfile=$TESTCONF all_resources
  cache:
    - <<: *smk_global_cache
      policy: pull
    - <<: *smk_envs_cache
      policy: pull
    - <<: *smk_resources_cache

snakemake_results:
  needs: [snakemake_resources, install_global_env]
  stage: test
  <<: *activate_smk
  script:
    - snakemake -p --use-conda -c 8 --configfile=$TESTCONF
  cache:
    - <<: *smk_global_cache
      policy: pull
    - <<: *smk_envs_cache
      policy: pull
    - <<: *smk_resources_cache
      policy: pull
