#!/bin/bash

#SBATCH --mail-type=ALL
#SBATCH --job-name=snakemake_ebm
#SBATCH --partition=batch
#SBATCH --time=1-12
#SBATCH --mem-per-cpu=64G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1

module load anaconda

conda activate snakemake-ebm

snakemake -p --verbose -r -j 1 --use-conda