#! /bin/bash

# Download a bed-like file (which could also be a vcf or genome file)

if [ "$1" = "gzip" ]; then
    curl -sS -L "$2" | gunzip -c
elif [ "$1" = "text" ]; then
    curl -sS -L "$2"
else
    echo "Unknown download format: $1"
    exit 1
fi
    
