#! /bin/bash

# Standardize chr column in a tab-delimited file:


col="$1"

cmd='BEGIN { FS = OFS = "\t" }'

# convert all complete nuclear chromosomes to integers (where X/Y are 23/24)
cmd+="{ sub(\"chr\", \"\", \$$col) }"
cmd+="{ sub(\"X\", \"23\", \$$col) }"
cmd+="{ sub(\"Y\", \"24\", \$$col) }"

# remove all incomplete chromosomes (and keep comments)
cmd+="{ if ( \$1 ~ /^#/ || \$$col ~ /^(1[0-9]|2[0-4]|[0-9])$/ ) { print } }"

awk "$cmd" -
