inputs:
  HG002_Element_DV:
    # chr_filter: &filter [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
    chr_filter: &filter [21]
    train:
      url: https://storage.googleapis.com/brain-genomics/awcarroll/share/giab/element/HG002.element.1.80x.dv1.4.vcf.gz
      ref: GRCh38
      benchmark: HG002_v4.2.1
    test:
      Clinvar_Element: &clinvar
        url: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive_2.0/2022/clinvar_20220812.vcf.gz
        ref: GRCh38
        # isn't genomics wonderful?
        chr_prefix: ''
        format_fields: {}
        benchmark: null
        format_fields:
          vaf: null
          dp: null
          gt: null
          gq: null
  HG002_Illumina_DV:
    train:
      chr_filter: *filter
      url: https://storage.googleapis.com/brain-genomics-public/research/sequencing/grch38/vcf/hiseqx/wgs_pcr_free/40x/HG002.hiseqx.pcr-free.40x.deepvariant-v1.0.grch38.vcf.gz
      ref: GRCh38
      benchmark: HG002_v4.2.1
    test:
      Clinvar_Illumina: *clinvar

ebm_runs:
  full_fp_v0:
    inputs:
      - HG002_Element_DV: [Clinvar_Element]
      - HG002_Illumina_DV: [Clinvar_Illumina]
    filter: [SNP, INDEL]
    ebm_settings: &ebm_settings
      split_parameters:
        test_size: 0.2
    error_labels: [fp]
    filtered_are_candidates: false
    interactions:
      - VCF_input
      - [VCF_indel_length, HOMOPOL_A_length]
      - [VCF_indel_length, HOMOPOL_T_length]
      - [VCF_indel_length, HOMOPOL_G_length]
      - [VCF_indel_length, HOMOPOL_C_length]
    features: &base_features
      VCF_input:
        feature_type: categorical
      VCF_VAF: {}
      VCF_DP:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 100}
      VCF_indel_length:
        visualization:
          truncate: {lower: -50, upper: 50}

      HOMOPOL_A_length: &homopol_length
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_T_length: *homopol_length
      HOMOPOL_G_length: *homopol_length
      HOMOPOL_C_length: *homopol_length
      HOMOPOL_A_imperfect_frac: &homopol_frac
        fill_na: -1
        visualization:
          split_missing: 0
      HOMOPOL_T_imperfect_frac: *homopol_frac
      HOMOPOL_G_imperfect_frac: *homopol_frac
      HOMOPOL_C_imperfect_frac: *homopol_frac

      TR_unit_size_max:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      TR_unit_copies_max:
        visualization:
          truncate: {lower: 0, upper: 50}
      TR_identity_min: {}
      TR_score_max: {}
      TR_percent_AT_median:
        fill_na: -1
        visualization:
          split_missing: 0

      REPMASK_SINE_length:
        transform: binary
        alt_name: REPMASK_SINE
        feature_type: categorical
      REPMASK_LTR_length:
        transform: binary
        alt_name: REPMASK_LTR
        feature_type: categorical
      REPMASK_LINE_length: {}

      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      SEGDUP_size_max: {}
      SEGDUP_identity_mean: {}
      SEGDUP_count:
        visualization:
          plot_type: bar
          truncate: {upper: 50}
