reference_sets:
  GRCh38_test:
    ref: GRCh38
    chr_filter: [21]

inputs:
  HG002_Hifi_DV:
    refset: GRCh38_test
    train:
      url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/SupplementaryFiles/inputvcfsandbeds/HG002_GRCh38_1_22_PacBio_HiFi_DeepVariant.vcf.gz
      benchmark: HG002_v4.2.1
    test:
      HG005_Hifi_DV:
        url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG005_NA24631_son/NISTv4.2.1/GRCh38/SupplementaryFiles/inputvcfsandbeds/HG005_GRCh38_1_22_PacBio_HiFi_DeepVariant.vcf.gz
        benchmark: HG005_v4.2.1
  HG002_Illumina_DV:
    refset: GRCh38_test
    train:
      url: https://storage.googleapis.com/brain-genomics-public/research/sequencing/grch38/vcf/hiseqx/wgs_pcr_free/40x/HG002.hiseqx.pcr-free.40x.deepvariant-v1.0.grch38.vcf.gz
      benchmark: HG002_v4.2.1
    test:
      Clinvar_Illumina:
        url: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive_2.0/2022/clinvar_20220812.vcf.gz
        # isn't genomics wonderful?
        chr_prefix: ''
        format_fields: {}
        benchmark: null
        # There are some super long variants in clinvar. Filter these out
        # because a) they would overlap with so many annotations that a new
        # universe would spawn into existance and b) they are outside what a
        # trained model would be good at testing anyways (until we incorporate
        # structural variants)
        format_fields:
          vaf: null
          dp: null
          gt: null
          gq: null

ebm_runs:
  small_set_v3:
    inputs:
      - HG002_Hifi_DV: [HG005_Hifi_DV]
        HG002_Illumina_DV: [Clinvar_Illumina]
    filter: [SNP, INDEL]
    ebm_settings: &ebm_settings
      split_parameters:
        test_size: 0.2
    error_labels: [fp]
    filtered_are_candidates: false
    interactions:
      - VCF_input
      - [VCF_indel_length, HOMOPOL_A_length]
      - [VCF_indel_length, HOMOPOL_T_length]
      - [VCF_indel_length, HOMOPOL_G_length]
      - [VCF_indel_length, HOMOPOL_C_length]
    features: &base_features
      VCF_input:
        feature_type: categorical
      VCF_VAF: {}
      VCF_DP:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 100}
      VCF_indel_length:
        visualization:
          truncate: {lower: -50, upper: 50}

      HOMOPOL_A_length: &homopol_length
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_T_length: *homopol_length
      HOMOPOL_G_length: *homopol_length
      HOMOPOL_C_length: *homopol_length
      HOMOPOL_A_imperfect_frac: &homopol_frac
        fill_na: -1
        visualization:
          split_missing: 0
      HOMOPOL_T_imperfect_frac: *homopol_frac
      HOMOPOL_G_imperfect_frac: *homopol_frac
      HOMOPOL_C_imperfect_frac: *homopol_frac

      TR_unit_size_max:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      TR_unit_copies_max:
        visualization:
          truncate: {lower: 0, upper: 50}
      TR_identity_min: {}
      TR_score_max: {}
      TR_percent_AT_median:
        fill_na: -1
        visualization:
          split_missing: 0

      REPMASK_SINE_length:
        transform: binary
        alt_name: REPMASK_SINE
        feature_type: categorical
      REPMASK_LTR_length:
        transform: binary
        alt_name: REPMASK_LTR
        feature_type: categorical
      REPMASK_LINE_length: {}

      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      SEGDUP_size_max: {}
      SEGDUP_identity_mean: {}
      SEGDUP_count:
        visualization:
          plot_type: bar
          truncate: {upper: 50}
